dataset:
  name: synthetic-11  # synthetic-<N> for synthetic datasets
  min_trajectory_length: 54  # Default value, adjust as necessary
  max_trajectory_length: 54  # Number of q wanted in input + n_y_prompts
  n_y_prompts: 4 # number of new questions to predict. default: 1
  max_context_length: 2048  # nb of tokens in context
  max_n_trajectories: 500  # 4/5 train, 1/5 test


model:
  type: lbm
  mode: steer
  q_per_batch: 1000  # Include all 
  filter_cid: 3  # Filter out questions with construct_id = 3
  additional_x_info: null  # No additional encoder info
  additional_bn_info: "$get_student_mastery:3"  # No additional bottleneck info
  max_bottleneck_tokens: 128  # default: 128
  encoder:
    name: Qwen/Qwen2.5-7B-Instruct
    use_cot: True
    max_cot_tokens: 1024
  decoder:
    name: Qwen/Qwen2.5-7B-Instruct
    use_cot: False
    max_cot_tokens: 1024

evaluation:
  batch_size: 5
  export_results: True
  export_path: "results/model_outputs"

wandb_tags: ['steer-test'] 